version: "3.9"

services:
  delivery-control-web:
    container_name: delivery-control-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
